server:
  port: 8080

zeebe:
  client:
    broker:
      contactpoint: ${ZEEBE_CLIENT_BROKER_CONTACTPOINT:127.0.0.1:26500}

openai:
  apiBaseUrl: https://api.openai.com/v1
  model: ${OPENAI_MODEL:gpt-5-mini}
  timeoutSec: 30
  maxRetries: 2
  apiKey: ${OPENAI_API_KEY} 